FROM scratch
ADD {{ rootfs_file }} /
# COPY turboacc /etc/config/turboacc
# COPY dhcp /etc/config/dhcp
# COPY firewall /etc/config/firewall
# COPY network /etc/config/network
# COPY resolv.conf /root/resolv.conf
# COPY rc.local /etc/rc.local
# COPY inittab /etc/inittab
# EXPOSE 80 443 22
CMD ["/sbin/init"]